### ISSUE TITLE
Allow authors to control each variable in Google Material Symbols

### ISSUE THREAD

**Issue by kuroda** [oiax/tgweb#125]
Authors should be able to state the following in the `site.toml`

```toml
[font.material-symbols]
outlined = true
rounded = { fill = 1, grad = 0, opsz = 24, wght = 200 }
sharp = { fill = 0, grad = 200, opsz = 40, wght = 300 }
```
