### ISSUE TITLE
Allow tg:toggler to prevent event propagation for displayed elements

### ISSUE THREAD

**Issue by kuroda** [oiax/tgweb#185]
The general technique used to prevent scrolling with the mouse wheel over an open hamburger menu is as follows:

```javascript
let toggleIsFixed = function(active) {
  const htmlElem = document.getElementsByTagName("html").item(0);
  if (active) htmlElem.classList.add("is-fixed")
  else htmlElem.classList.remove("is-fixed");
}
```

```css
html.is-fixed,
html.is-fixed body {
  height: 100%;
  overflow: hidden;
}
```

Consider using the Event.stopPropagation() method.
